[build]
  command = "CI=false npm run build"
  publish = "build"
  functions = "functions"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[context.production.environment]
  ALCHEMY_RINKEBY = "https://eth-goerli.g.alchemy.com/v2/iVdQ5frXbmIvL17Cei12tckgBCRuGxUE"
  CI = "false"
  GANACHE_URL = "HTTP://127.0.0.1:8545"
  PRIVATE_KEY = "0xAe752E7A439Ccf3C29d351Bf59f54dC2A7D97F67"
  REACT_APP_RPC_ADDRESS = "https://goerli.infura.io/v3/bd3283c53475479792ed8f68c398a0e9"

[context.deploy-preview.environment]
  ALCHEMY_RINKEBY = "https://eth-goerli.g.alchemy.com/v2/iVdQ5frXbmIvL17Cei12tckgBCRuGxUE"
  CI = "false"
  GANACHE_URL = "HTTP://127.0.0.1:8545"
  PRIVATE_KEY = "0xAe752E7A439Ccf3C29d351Bf59f54dC2A7D97F67"
  REACT_APP_RPC_ADDRESS = "https://goerli.infura.io/v3/bd3283c53475479792ed8f68c398a0e9"

[context.branch-deploy.environment]
  ALCHEMY_RINKEBY = "https://eth-goerli.g.alchemy.com/v2/iVdQ5frXbmIvL17Cei12tckgBCRuGxUE"
  CI = "false"
  GANACHE_URL = "HTTP://127.0.0.1:8545"
  PRIVATE_KEY = "0xAe752E7A439Ccf3C29d351Bf59f54dC2A7D97F67"
  REACT_APP_RPC_ADDRESS = "https://goerli.infura.io/v3/bd3283c53475479792ed8f68c398a0e9"

[context.branch-deploy.environment]
  ALCHEMY_RINKEBY = "https://eth-goerli.g.alchemy.com/v2/iVdQ5frXbmIvL17Cei12tckgBCRuGxUE"
  CI = "false"
  GANACHE_URL = "HTTP://127.0.0.1:8545"
  PRIVATE_KEY = "0xAe752E7A439Ccf3C29d351Bf59f54dC2A7D97F67"
  REACT_APP_RPC_ADDRESS = "https://goerli.infura.io/v3/bd3283c53475479792ed8f68c398a0e9"

[build.environment]
  CI = "false"
